# Generated by Django 3.2 on 2023-12-09 09:08

from django.db import migrations, models
import django.db.models.deletion
import puzzles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to=puzzles.models.upload_to_puzzles)),
                ('row', models.PositiveIntegerField(default=5)),
                ('column', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': 'Puzzle',
            },
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=puzzles.models.upload_to_puzzle_images)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
            options={
                'verbose_name_plural': 'Puzzle Images',
            },
        ),
    ]
