# Generated by Django 3.2 on 2023-12-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleimage',
            name='col',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzleimage',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
