# Generated by Django 3.2 on 2023-12-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('puzzles', '0005_alter_puzzleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
