# Generated by Django 3.2 on 2023-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_puzzle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
