# Generated by Django 3.2 on 2023-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_puzzle_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='is_locked',
        ),
    ]
